!------------------------ General Init -----------------------
!-------------------------------------------------------------

&tao_design_lattice
 n_universes = 1
 design_lattice(1) = 'Pass11_Test1.bmad@Pass11'
/

!------------------------ Variables --------------------------
!-------------------------------------------------------------

&tao_var
 v1_var%name = 'Pass11'
! var(1)%ele_name = 'ov9_3'
! var(1)%attribute = 'Ang1'
! var(1)%step = 1e-4
 var(1)%ele_name = 'M9Q1'
 var(1)%attribute = 'k1'
 var(1)%step = 1e-5
 var(2)%ele_name = 'M9Q1'
 var(2)%attribute = 'vkick'
 var(2)%step = 1e-4
! var(3)%ele_name = 'M7Q1'
! var(3)%attribute = 'k1'
! var(3)%step = 1e-5
! var(4)%ele_name = 'ov7_6'
! var(4)%attribute = 'k1'
! var(4)%high_lim = 1.9
! var(4)%step = 1e-5
! var(5)%ele_name = 'M5Q4'
! var(5)%attribute = 'k1'
! var(5)%step = 1e-5
/

!------------------------ Data -------------------------------
!-------------------------------------------------------------

&tao_d2_data
 universe = '1'
 d2_data%name = 'Pass11'
 n_d1_data = 2
/

!&tao_d1_data			! This one places the y-coordinates, so that the optimizer can place dipoles correctly.
! ix_d1_data = 1
! d1_data%name = 'geometry'
! default_weight = 1
! datum(1)%data_type = 'floor.y'
! datum(1)%ele_name = 'D905' 
! datum(1)%meas = 100.0000000000000000000000000000000000
!/

&Tao_d1_data			! This one places the y-coordinates, so that the optimizer can place dipoles correctly.
 ix_d1_data = 1
 d1_data%name = 'DispersionY'
 default_weight = 10000000
 datum(1:2)%data_type = 'eta.y' 'etap.y'
 datum(1:2)%ele_name =  'po_11RBCOM1_yoffset' 'po_11RBCOM1_yoffset'
 datum(1:2)%meas = 0.00000000000000000 0.00000000000000000000 
/

&Tao_d1_data
 ix_d1_data = 2
 d1_data%name = 'DispersionY_2'
 default_weight = 1000
 datum(1:2)%data_type = 'eta.y' 'etap.y'   
 datum(1:2)%ele_name = 'END' 'END' !'po_11RBCOM1_yoffset' 'po_11RBCOM1_yoffset'
 datum(1:2)%meas = 0 
/


&tao_params
 global%blank_line_between_commands = f
 global%draw_curve_off_scale_warn = f
 global%history_file = '.history_tao'
 global%lmdif_negligible_merit = 1e-60
 global%n_opti_cycles = 128
 global%symbol_import = t
 global%var_limits_on = f
/

