FROM ubuntu:focal

RUN mkdir -p /run/systemd && echo 'docker' > /run/systemd/container

CMD ["/bin/bash"]

WORKDIR /tmp

# start with more uptodate packages
RUN apt-get update

# build essentials 
RUN DEBIAN_FRONTEND="noninteractive" apt -y install build-essential

# required packages
RUN DEBIAN_FRONTEND="noninteractive" apt-get -y install cmake cmake-curses-gui wget xorg-dev freeglut3-dev qt5-default python2.7-dev libssl-dev liblz4-dev git \
    libxerces-c-dev bison flex python3-pip python-tk x11vnc xvfb fvwm

# python packages
RUN pip3 install scipy matplotlib numpy ipython

# clhep
RUN wget http://proj-clhep.web.cern.ch/proj-clhep/dist1/clhep-2.4.1.3.tgz --no-check-certificate && \
    tar -xf clhep-2.4.1.3.tgz && rm -rf clhep-2.4.1.3.tgz && \
    mkdir 2.4.1.3-build && cd 2.4.1.3-build && cmake ../2.4.1.3/CLHEP/ && \
    make -j6 && make install && cd ../ && rm -rfv 2.4.1.3 2.4.1.3-build

# root
RUN nproc
#RUN wget https://root.cern/download/root_v6.20.00.source.tar.gz && \
#    tar zxf root_v6.20.00.source.tar.gz && mkdir root-6.20.00-build && \
#    cd root-6.20.00-build && cmake ../root-6.20.00 && make -j`nproc` && make install 
    #  && \ cd ../ && rm -rfv root-6.20.00-build root-6.20.00

RUN wget https://root.cern/download/root_v6.20.00.source.tar.gz && \
    tar zxf root_v6.20.00.source.tar.gz && mkdir root-6.20.00-build && \
    cd root-6.20.00-build && cmake ../root-6.20.00 && make -j`nproc` 2>&1 | tee make.log && make install

# geant4
RUN wget https://github.com/Geant4/geant4/archive/v10.4.3.tar.gz && \
    tar zxf v10.4.3.tar.gz && mkdir geant4-10.4.3-build && cd geant4-10.4.3-build && \
    cmake ../geant4-10.4.3 -DGEANT4_INSTALL_DATA=ON -DGEANT4_USE_GDML=ON -DGEANT4_USE_OPENGL_X11=ON \
    -DGEANT4_USE_SYSTEM_CLHEP=ON -DGEANT4_USE_QT=ON -DGEANT4_USE_RAYTRACER_X11=ON && make -j`nproc` && make install 

SHELL ["/bin/bash", "-c"]

# BDSIM
#RUN git clone https://bitbucket.org/jairhul/bdsim.git && cd bdsim && git checkout v1.7.0 && cd ../ && \
#    . /usr/local/bin/thisroot.sh && mkdir bdsim-build && cd bdsim-build && cmake ../bdsim && make -j`nproc` && make install
    # && \ cd ../ && rm -rfv bdsim-build bdsim 

RUN git clone https://github.com/bdsim-collaboration/bdsim && cd bdsim && git checkout v1.7.7 && cd ../ && \
    . /usr/local/bin/thisroot.sh && mkdir bdsim-build && cd bdsim-build && cmake ../bdsim && make -j`nproc` && make install
    # && \ cd ../ && rm -rfv bdsim-build bdsim 

# Python support tools (pybdsim, pymadx, pymad8, pytransport, pyg4ometry)
RUN pip3 install pybdsim pymadx pymad8 pytransport ipython

RUN echo 'source /usr/local/bin/geant4.sh' >> ~/.bashrc && \
    echo 'export PYTHONPATH=$PYTHONPATH:/usr/local/lib' >> ~/.bashrc && \
    echo 'source /usr/local/bin/bdsim.sh' >> ~/.bashrc
   