#!/bin/bash
#
wrks=$1
: ${wrks:="Optics"}
echo "importing Hall B 4th pass"
elegant ihb4.ele >/dev/null
importCED ihb4 >/dev/null
sddsprocess -filter=col,s,5.098702e+03,1e10 dipoles.sdds dipoles4.sdds 
sddsprocess -filter=col,s,5.098702e+03,1e10 MONITORS.sdds monitors4.sdds 
sddsprocess -filter=col,s,5.098702e+03,1e10 quads.sdds quads4.sdds 
sddsprocess -filter=col,s,5.098702e+03,1e10 kickers.sdds kickers4.sdds 
echo "importing dipoles"
/cs/dvlhome/apps/c/CED/dvl/src/12GeV/loadSDDS.pl -wrkspc=$wrks \
 -proplist=s,L,betax,alphax,betay,alphay,etax,etay,etapx,etapy,psix,psiy,pCentral,HGAP,E1,E2,ANGLE,K1,sigmax,sigmay,ecx,ecy,ModelX,ModelY,ModelZ,theta,phi,psi\
 -startpass=4 -extract -sdds=dipoles4.sdds
cp loadsdds.err loadsdds_hb4dip.err
echo "importing monitors"
/cs/dvlhome/apps/c/CED/dvl/src/12GeV/loadSDDS.pl -wrkspc=$wrks \
 -proplist=s,L,betax,alphax,betay,alphay,etax,etay,etapx,etapy,psix,psiy,pCentral,sigmax,sigmay,ecx,ecy,ModelX,ModelY,ModelZ,phi,theta,psi\
 -startpass=4 -sdds=monitors4.sdds
cp loadsdds.err loadsdds_hb4mon.err
echo "importing quads"
/cs/dvlhome/apps/c/CED/dvl/src/12GeV/loadSDDS.pl -wrkspc=$wrks \
 -proplist=s,L,betax,alphax,betay,alphay,etax,etay,etapx,etapy,psix,psiy,pCentral,K1,sigmax,sigmay,ecx,ecy,Tilt,theta,phi,psi,ModelX,ModelY,ModelZ\
 -startpass=4 -sdds=quads4.sdds
cp loadsdds.err loadsdds_hb4quad.err
echo "importing kickers"
/cs/dvlhome/apps/c/CED/dvl/src/12GeV/loadSDDS.pl -wrkspc=$wrks \
 -proplist=s,L,betax,alphax,betay,alphay,etax,etay,etapx,KICK,etapy,psix,psiy,pCentral,sigmax,sigmay,ecx,ecy,ModelX,ModelY,ModelZ,phi,theta,psi\
 -startpass=4 -sdds=kickers4.sdds
cp loadsdds.err loadsdds_hb4kick.err
