#!/bin/bash
# start at lambertson
# shift Y coord to be at 99.978 
#
wrks=$1
: ${wrks:="Optics"}
echo "importing  Hall C 1st pass"
#
# it is at 99.978 which is 2.2 cm below HALLB 
#
# restrict to first pass HALLC
# when we import HALLA, we import the BSY with it.
# for B, and C we can skip the BSY import.
# only works on fresh ihc file otherwise we may 
# add up offset more than once so explicitely run elegant.
# cutoff is right in front of lambertson
#
elegant ihc1.ele >/dev/null
sddsprocess -filter=col,s,1.165212e+03,1e10 ihc1.twi ihc1.twi
sddsprocess -filter=col,s,1.165212e+03,1e10 ihc1.cen ihc1.cen
sddsprocess -filter=col,s,1.165212e+03,1e10 ihc1.flr ihc1.flr
sddsprocess -filter=col,s,1.165212e+03,1e10 ihc1.sig ihc1.sig
sddsprocess -redefine=col,Y,"Y 0.022 -" ihc1.flr ihc1.flr
#
importCED ihc1 >/dev/null
cp dipoles.sdds dipoles1.sdds
cp MONITORS.sdds monitors1.sdds
cp kickers.sdds kickers1.sdds
cp quads.sdds quads1.sdds
cp sextupoles.sdds sextupoles1.sdds
cp solenoids.sdds solenoids1.sdds
echo "importing solenoids"
/cs/dvlhome/apps/c/CED/dvl/src/12GeV/loadSDDS.pl -wrkspc=$wrks \
 -proplist=s,L,betax,alphax,betay,alphay,etax,etay,etapx,etapy,psix,psiy,pCentral,KS,sigmax,sigmay,ecx,ecy,theta,phi,psi,X,Y,Z\
 -startpass=1 -sdds=solenoids1.sdds
cp loadsdds.err loadsdds_hc1sol.err
echo "importing dipoles"
/cs/dvlhome/apps/c/CED/dvl/src/12GeV/loadSDDS.pl -wrkspc=$wrks \
 -proplist=s,L,betax,alphax,betay,alphay,etax,etay,etapx,etapy,psix,psiy,pCentral,HGAP,E1,E2,ANGLE,K1,sigmax,sigmay,ecx,ecy,ModelX,ModelY,ModelZ,theta,phi,psi\
 -startpass=1 -extract -sdds=dipoles1.sdds
cp loadsdds.err loadsdds_hc1dip.err
echo "importing monitors"
/cs/dvlhome/apps/c/CED/dvl/src/12GeV/loadSDDS.pl -wrkspc=$wrks \
 -proplist=s,L,betax,alphax,betay,alphay,etax,etay,etapx,etapy,psix,psiy,pCentral,sigmax,sigmay,ecx,ecy,ModelX,ModelY,ModelZ,phi,theta,psi\
 -startpass=1 -sdds=monitors1.sdds
cp loadsdds.err loadsdds_hc1mon.err
echo "importing quads"
/cs/dvlhome/apps/c/CED/dvl/src/12GeV/loadSDDS.pl -wrkspc=$wrks \
 -proplist=s,L,betax,alphax,betay,alphay,etax,etay,etapx,etapy,psix,psiy,pCentral,K1,sigmax,sigmay,ecx,ecy,Tilt,theta,phi,psi,ModelX,ModelY,ModelZ\
 -startpass=1 -sdds=quads1.sdds
cp loadsdds.err loadsdds_hc1quad.err
echo "importing kickers"
/cs/dvlhome/apps/c/CED/dvl/src/12GeV/loadSDDS.pl -wrkspc=$wrks \
 -proplist=s,L,betax,alphax,betay,alphay,etax,etay,etapx,KICK,etapy,psix,psiy,pCentral,sigmax,sigmay,ecx,ecy,ModelX,ModelY,ModelZ,phi,theta,psi\
 -startpass=1 -sdds=kickers1.sdds
cp loadsdds.err loadsdds_hc1kick.err
echo "importing sextupoles"
/cs/dvlhome/apps/c/CED/dvl/src/12GeV/loadSDDS.pl -wrkspc=$wrks \
 -proplist=s,L,betax,alphax,betay,alphay,etax,etay,etapx,etapy,psix,psiy,pCentral,K2,sigmax,sigmay,ecx,ecy,Tilt,theta,phi,psi,ModelX,ModelY,ModelZ\
 -startpass=1 -sdds=sextupoles1.sdds
cp loadsdds.err loadsdds_hc1sext.err
