#!/bin/bash
# start at RRF6E00A
#  3.679513e+03 
#
wrks=$1
: ${wrks:="Optics"}
echo "importing 1/4 cryo to Hall C 3rd pass"
elegant ihc3.ele >/dev/null
sddsprocess -redefine=col,Y,"Y 0.022 -" ihc3.flr ihc3.flr
importCED ihc3 >/dev/null
sddsprocess -filter=col,s,3.679512e+03,1e10 dipoles.sdds dipoles3.sdds 
sddsprocess -filter=col,s,3.679512e+03,1e10 MONITORS.sdds monitors3.sdds 
sddsprocess -filter=col,s,3.679512e+03,1e10 quads.sdds quads3.sdds 
sddsprocess -filter=col,s,3.679512e+03,1e10 kickers.sdds kickers3.sdds 

echo "importing dipoles"
/cs/dvlhome/apps/c/CED/dvl/src/12GeV/loadSDDS.pl -wrkspc=$wrks \
 -proplist=s,L,betax,alphax,betay,alphay,etax,etay,etapx,etapy,psix,psiy,pCentral,HGAP,E1,E2,ANGLE,K1,sigmax,sigmay,ecx,ecy,ModelX,ModelY,ModelZ,theta,phi,psi\
 -startpass=3 -extract -sdds=dipoles3.sdds
echo "importing monitors"
/cs/dvlhome/apps/c/CED/dvl/src/12GeV/loadSDDS.pl -wrkspc=$wrks \
 -proplist=s,L,betax,alphax,betay,alphay,etax,etay,etapx,etapy,psix,psiy,pCentral,sigmax,sigmay,ecx,ecy,ModelX,ModelY,ModelZ,phi,theta,psi\
 -startpass=3 -sdds=monitors3.sdds
echo "importing quads"
/cs/dvlhome/apps/c/CED/dvl/src/12GeV/loadSDDS.pl -wrkspc=$wrks \
 -proplist=s,L,betax,alphax,betay,alphay,etax,etay,etapx,etapy,psix,psiy,pCentral,K1,sigmax,sigmay,ecx,ecy,Tilt,theta,phi,psi,ModelX,ModelY,ModelZ\
 -startpass=3 -sdds=quads3.sdds
echo "importing kickers"
/cs/dvlhome/apps/c/CED/dvl/src/12GeV/loadSDDS.pl -wrkspc=$wrks \
 -proplist=s,L,betax,alphax,betay,alphay,etax,etay,etapx,KICK,etapy,psix,psiy,pCentral,sigmax,sigmay,ecx,ecy,ModelX,ModelY,ModelZ,phi,theta,psi\
 -startpass=3 -sdds=kickers3.sdds
