#!/usr/bin/perl
# this script calculates the proper quadrupole scaling for a new linac profile.
# 
my $injGAIN=$ARGV[0];
my $gainNL=$ARGV[1];
my $gainSL=$ARGV[2];
my $ratioNL=$gainNL/1090;
my $ratioSL=$gainSL/1090;
my $startNL=$injGAIN;
#123.0/1090.0*$gainNL;
my $startSL=$startNL+$gainNL;
my $endSL=$startSL+$gainSL;
print "start NL is $startNL\n";
print "start SL is $startSL\n";
print "start reinj is $endSL\n";
print "ratios are $ratioNL $ratioSL\n";
system("elegant NL.ele >/dev/null");
system("elegant SL.ele >/dev/null");
system("elegant REINJ3.ele >/dev/null");
my $cmd1s="sddsprocess -define=column,sc,\"$startSL 0.511 / pCentral 1213 0.511 / - $ratioSL * + pCentral / \" SL.cen SLscale.sdds";
my $cmd2s="sddsprocess -define=column,sc,\"$startNL 0.511 / pCentral 123 0.511 / - $ratioNL * + pCentral / \" NL.cen NLscale.sdds";
my $cmd3s="sddsprocess -define=column,sc,\"$endSL 0.511 / pCentral 2303 0.511 / - $ratioSL * + pCentral / \" REINJ3.cen REINJscale.sdds";
system($cmd1s);
system($cmd2s);
system($cmd3s);
system("sddsprocess -match=column,ElementParameter=B NL.parms NLB.parms");
system("sddsprocess -match=column,ElementParameter=B SL.parms SLB.parms");
system("sddsprocess -match=column,ElementParameter=B REINJ3.parms REINJB.parms");
system("sddsxref NLB.parms NLscale.sdds -match=ElementName -pipe=out|sddsprocess -pipe=in -define=column,Bnew,\"ParameterValue sc *\" NLQuads.sdds");
system("sddsxref SLB.parms SLscale.sdds -match=ElementName -pipe=out|sddsprocess -pipe=in -define=column,Bnew,\"ParameterValue sc *\" SLQuads.sdds");
system("sddsxref REINJB.parms REINJscale.sdds -match=ElementName -pipe=out|sddsprocess -pipe=in -define=column,Bnew,\"ParameterValue sc *\" REINJQuads.sdds");
system("sddsprocess -redefine=column,ParameterValue,\"Bnew\" SLQuads.sdds SLq.sdds");
system("sddsprocess -redefine=column,ParameterValue,\"Bnew\" NLQuads.sdds  NLq.sdds");
system("sddsprocess -redefine=column,ParameterValue,\"Bnew\" REINJQuads.sdds REINJq.sdds")
